<?php
/*
 * 2008-01-05
 * http://drupal.org/node/44648 http://drupal.org/node/209336
 * $Id: block_example.module,v 1.9 2007/07/06 18:16:15 drewish Exp $
 */

function epBookNav_block($op = 'list', $delta = 0, $edit = array())
{
	$blocks = array();
	if($op == 'list') {
		$blocks[0] = array('info' => t('epBookNav_block'),
			'status' => TRUE, 
			'weight' => 0, 
			'visibility' => 1, 
			'region' => 'right',
			'pages' => 'node/*',
			'cache' => BLOCK_NO_CACHE,
		);
	}
	elseif($op == 'view') {
		$blocks['subject'] = t('Browse the Sections');
		$blocks['content'] = epBookNav_content();
		drupal_add_js(path_to_theme().'/includes/jquery-accordion/jquery.accordion.js');
		drupal_add_js(epBookNav_content_js(), 'inline', 'footer');
	}
	return $blocks;
}

/**
 * A block content function
 */
function epBookNav_content()
{
	/*if($node = menu_get_object()) {
		$current_bid = empty($node->book['bid']) ? 0 : $node->book['bid'];
	}*/
	$book_menus = array();
	foreach(book_get_books() as $book_id => $book) 
	{
		$node = node_load($book['nid']);
		$book_menus[$book_id] = menu_tree_output(menu_tree_all_data($node->book['menu_name']));
	}
	$css = '<style type="text/css">.epBookNav_content ul li.collapsed { background-image: url("/sites/all/themes/elephantparents/images/ep-menu-collapsed.gif") } .epBookNav_content ul li.expanded { background-image: url("/sites/all/themes/elephantparents/images/ep-menu-expanded.gif") }</style>';
	return '<div class="epBookNav_content">'. theme('book_all_books_block', $book_menus) . $css .'</div>';
}

function epBookNav_content_js()
{
	$js = <<<EOT

$('.epBookNav_content a.active').parents('li').addClass('active');
$('.epBookNav_content li').each(function() 
{ 
	target = $(this).find('ul:first');
	if(target.length < 1) return;
	$(target).not('.active').hide().parent('li').removeClass('expanded').addClass('collapsed');
	link = $(this).prepend('<span></span>').find('span').attr('style', 'position:absolute;left:3em;width:2em;height:1em;');	
	$(link).toggle(
		function() {
			$(this).addClass('expanded').removeClass('collapsed');
			$(target).slideDown('slow');
		}, 
		function() {
			$(this).addClass('collapsed').removeClass('expanded');
			$(target).fadeOut(500);
	});
});

EOT;
	return $js;
}

