<?php
/*
 * Some quick hooks for moving question-type nodes
 * to question-answer style
 */

function epQuestions_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) 
{
	if($node->type == 'question') 
	{
		if($op == 'presave' && !user_access('administer comments') && empty($node->title) || $node->title == 'Question') 
		{
			$pos = (strpos($node->body, ' ', 50)) ? strpos($node->body, ' ', 50) : 50; // first \s after 50
			$node->title = ucwords(strtolower(substr($node->body, 0, $pos) .'...'));
		}
	}
	
}

function epQuestions_form_alter(&$form, $form_state, $form_id) 
{
	global $user;
	// hide the title field for non-admins
	if($form_id == 'question_node_form' && !user_access('administer comments')) { 
		$form['title']['#type'] = 'hidden';
		$form['title']['#default_value'] = 'Question';
		$form['body_field']['body']['#title'] = 'Your Question';
	}
	if($form_id == 'user_register') {
		drupal_set_message(t('I should not see this 2'), 'error');
		$form['#submit'][] = 'epQuestions_new_user_notify';
	}
}


function epQuestions_user($op, &$edit, &$account, $category = NULL) 
{
	if($op == 'insert') {
		$u = user_load($account->uid); // get full user object with profile fields
		if($u->profile_request_professional || $u->profile_request_columnist) {
			$params = array(
				'subject' => 'New user request',
				'body' => array(
					"A new user (". $u->mail .") has requested special status on the site.",
					($u->profile_request_professional) ? "\t[ x ]Professional Status" : "\t[   ]Professional Status",
					($u->profile_request_columnist) ? "\t[ x ]Columnist Status" : "\t[   ]Columnist Status",
					"\t". strip_tags($u->profile_request_details),
					"\nTo activate, deactivate or change user settings, visit ". url('admin/user', array('absolute'=>true)) .".",
					"\nThank you!",
					),
				);
			$r = drupal_mail('epQuestions', 'user_registration_requests', 'admin@elephantparents.com', language_default(), $params);
		}
	}
}

function epQuestions_mail($key, &$message, $params) 
{
	$language = $message['language'];
	$variables = user_mail_tokens($params['account'], $language);
	if($key == 'user_registration_requests') {
		$message['subject'] = $params['subject'];
		$message['body'] = $params['body'];
	}
}

function null_epQuestions_db_rewrite_sql($query, $primary_table, $primary_field, $args) {
}
function null_epQuestions_link_alter(&$links, $node) {
}
function null_epQuestions_comment(&$a1, $op) {
}
function null_epQuestions_preprocess_comment_wrapper(&$variables) {
}
function null_epQestions_comment_block() {
}



